apiVersion: batch/v1
kind: Job
metadata:
  name: populating-db
  namespace: default
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: populating-db
        image: mrconfetti/populate-db:latest
      restartPolicy: OnFailure