FROM python:3.6
WORKDIR /usr/src/app
COPY . .
RUN pip3 install --upgrade pip
RUN pip3 install elasticsearch
RUN pip3 install kafka-python
RUN apt-get update
RUN apt-get install -y vim
CMD ["producer.py"]
ENTRYPOINT [ "python3" ]
