apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer
  strategy: {}
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        io.kompose.service: consumer
    spec:
      containers:
        - image: sjinde/scalable:consumer
          name: consumer
          resources: {}
      hostname: consumer
      restartPolicy: Always
status: {}