---
version: "3.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    networks:
      - stream-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
    - stream-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - stream-network
    ports:
      - 9092:9092
      - 30001:30001
      - 9093:9093
    environment:
      KAFKA_CREATE_TOPICS: stream
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  spark-leader:
    image: sjinde/spark-leader:0.1
    container_name: spark-leader
    networks:
      - stream-network
    volumes:
      - ./:/scripts/
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - SPARK_LOCAL_IP=spark-leader
      - INIT_DAEMON_STEP=setup_spark
      - PYSPARK_PYTHON=python3.4
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER=spark://spark-master:7077
    command: /start-leader.sh

  spark-worker-1:
    image: sjinde/spark-worker:0.1
    container_name: spark-worker-1
    volumes:
      - ./:/scripts/
    networks:
      - stream-network
    depends_on:
      - spark-leader
    ports:
      - 8080
    environment:
      - PYSPARK_PYTHON=python3.4
      - SPARK_MASTER=spark://spark-leader:7077
      - SPARK_WORKER_WEBUI_PORT=8080
    command: /start-worker.sh

  populate_db:
    build:
      context: .
      dockerfile: Dockerfile.populate
    container_name: populate_db
    depends_on:
      - elasticsearch
    networks:
      - stream-network
    restart: on-failure

  producer:
    build:
      context: .
      dockerfile: ./Dockerfile.producer
    container_name: producer
    depends_on:
      - kafka
    networks:
      - stream-network

  client:
      image: appropriate/curl:latest
      depends_on:
      - elasticsearch
      networks:
        - stream-network
      command: "curl http://elasticsearch:9200"

networks:
  stream-network:
    driver: "bridge"
