apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark-driver
  name: spark-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-driver
  strategy: {}
  template:
    metadata:
      labels:
        app: spark-driver
    spec:
      containers:
        - image: mrconfetti/spark-jupyter
          name: spark-driver
          ports:
            - containerPort: 8888
            - containerPort: 4040
      hostname: spark-driver
