apiVersion: v1
kind: Service
metadata:
  name: kibana-proc
  namespace: default
  labels:
    app: kibana-proc
spec:
  type: NodePort
  ports:
  - port: 5601
  selector:
    app: kibana-proc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-proc
  namespace: default
  labels:
    app: kibana-proc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana-proc
  template:
    metadata:
      labels:
        app: kibana-proc
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.11.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch-proc:9200
        ports:
        - containerPort: 5601