version: '3'

networks:
  spark-communication:
    external: true

services:
  spark-driver:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/richardswesterhof/mapreduce:latest
    hostname: spark-driver
    networks:
      # join the external network for spark communication
      # this does mean the mapreduce cannot run without the spark cluster running in kubernetes
      # but this wouldn't really make sense anyway
      - spark-communication
    ports:
      - '30001:30001'
      - '30002:30002'
